id = "vscode-dark-modern"
name = "VSCode Themes"
version = "0.2.0"
schema_version = 1
authors = ["kcamcam <kevincamellini@gmail.com>"]
description = "VSCode Dark Modern, VSCode Dark, and VSCode Light Themes for Zed"
repository = "https://github.com/kcamcam/vscode_dark_modern.zed"
themes = ["themes/vscode-dark-modern.json", "themes/vscode-dark.json", "themes/vscode-light.json"]
